import { Roboto_Mono } from 'next/font/google';

import Header from '@/components/Header';
import { Providers } from '@/components/Provider';

import type { Metadata } from 'next';

import '../assets/styles/globals.css';

const robotoSans = Roboto_Mono({
	variable: '--font-roboto-sans',
	subsets: ['latin']
});

export const metadata: Metadata = {
	title: 'LastBite',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${robotoSans.variable} antialiased overflow-y-hidden`}>
				<Header />
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
