import { Roboto } from 'next/font/google';

import Header from '@/components/Header';
import { Providers } from '@/components/Provider';

import type { Metadata } from 'next';

import '../assets/styles/globals.css';

const roboto = Roboto({
	weight: '400',
	subsets: ['cyrillic']
});

export const metadata: Metadata = {
	title: 'LastBite',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${roboto.style.fontFamily}`}>
				<Header />
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
